com:
  kris:
    datasource:
      prophecy:
        url: jdbc:mysql://localhost:3306/prophecy?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: debian-sys-maint
        password: 33NfmKUDjW6n5PHD

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: kris0424
    blockWhenExhausted: true
    jedisPoolMaxIdle: 200
    jedisPoolTimeout: 10000
  data:
    mongodb:
      uri: mongodb://Kris:kris0424@localhost:27017/prophecy
  application:
    name: prophecy

thread:
  pool:
    corePoolSize: 10
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50

#eureka:
#  client:
#    serviceUrl:
#      defaultZone : http://localhost:8761/eureka/

kafka:
  consumer:
    zookeeperConnect: 192.168.0.103:2181
    servers: 192.168.0.103:9092
    enableAutoCommit: true
    sessionTimeout: 6000
    autoCommitInterval: 100
    autoOffsetReset: latest
    topic: test
    groupId: test
    concurrency: 10

  producer:
    servers: 192.168.0.103:9092
    retries: 0
    batchSize: 4096
    linger: 1
    bufferMemory: 40960

#logging:
#  level:
#    com:
#      kris:
#        prophecy: debug
logging:
  config: classpath:log4j2-dev.xml

#百度翻译语言识别
language:
  url: https://fanyi.baidu.com/langdetect
# 经纬度地址解析
address:
  url: http://apis.juhe.cn/geo
  key: 2bc57d818e18d1cbe33748124b12dd10
  timeOut: 5000
  isEnable: true
# 旷视人脸检测
face:
  url: https://api-cn.faceplusplus.com/facepp/v3/detect
  apiKey: fPd1ep8kXcdKvcAXUPswDpTGxwkPNb3O
  apiSecret: Ris2AFcKzjmqgUXXbi99bmPio0_lamBS
  returnAttributes: gender,skinstatus,beauty,age,emotion
  timeOut: 5000
  isEnable: true
# 影讯集合
movie:
  url: http://v.juhe.cn/movie/index
  key: 0d8f7a7d1cfb1c3e1275ec931b154fa2
  timeOut: 5000
  isEnable: true
# 手机归属地
mobile:
  url: http://tcc.taobao.com/cc/json/mobile_tel_segment.htm
  timeOut: 5000
  isEnable: true