spring:
  cloud:
    consul:
      discovery:
        ##检测实例健康
        health-check-path: /actuator/health
        ##每隔10s检查
        health-check-interval: 10s
        ##自动注册
        register: true
        ##实例名称
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        ##启动服务发现
        enabled: true
        prefer-ip-address: true
      #consul地址
      host: localhost
      port: 8500
      config:
        enabled: true
        ##配置中心解析样式
        format: yaml
  profiles:
    active: dev
  application:
    name: prophecy

server:
  port: 8888

ribbon:
  # ribbon缓存时间，默认30秒
  ServerListRefreshInterval: 2000
  ReadTimeout: 5000
  ConnectTimeout: 5000
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false
  # 重试负载均衡其他的实例最大重试次数,不包括首次server（查询项目可开启）
  MaxAutoRetriesNextServer: 0
  # 同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0

call-class:
  map:
    D000: 大数据输出
    D001: 语言识别
    D002: 经纬度地址解析
    D003: 人脸检测
    D004: 影讯合集
    D005: 手机归属地
    D006: 国家数据